---
php_version: "8.1"
php:
  - php{{ php_version }}
  - php{{ php_version }}-common
  - php{{ php_version }}-curl
  - php{{ php_version }}-fpm
  - php{{ php_version }}-gd
  - php{{ php_version }}-imagick
  - php{{ php_version }}-intl
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-mysql
  - php{{ php_version }}-xml
  - php{{ php_version }}-xmlrpc
  - php{{ php_version }}-zip
